# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 31cf361bc902bb0696bbb01124fc2d689d63e6d51e037f5bc7f11efaf1337ea07983c944531f0f9b9b947ac214ae0ac71025847ebb5463e03b378a19400f567d

test:
  secret_key_base: cf52fdd5faedd50dde0b24196403df20a8c5d4c71999b7e159aaca74b71a10bce028536d72a473732c992a175f188460b0c2e29b4cf6096db8f68c89303b4b6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
